### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by fr3d3lin** [DavideBlade/HealthBar-Reloaded#10]
i have paper 1.17.1 server an i have this error in my consol

[21:44:09 WARN]: [HealthBar-Reloaded] Task #12906 for HealthBar-Reloaded v2.0.3.3 generated an exception
java.lang.ArrayIndexOutOfBoundsException: null

the ''task'' number still going up

**Comment by DavideBlade** [comment]
Please send me all the .yml files in the plugin folder. Also, is there anything else in the console or is that the only error?

**Comment by DavideBlade** [comment]
No response. Bug not reproducible/wrongly opened.
