### ISSUE TITLE
Plugin seems to un-dinnerbone mobs.

### ISSUE THREAD

**Issue by surfrock66** [DavideBlade/HealthBar-Reloaded#11]
I had a dog that was dinnerboned to be upside down.  Now that I turned this on, he flips right side up.  If I re-dinnerbone him, he flips back when the health bar shows.  I can re-flip him, it appears to happen on render.

**Comment by DavideBlade** [comment]
Can you define what you mean by 'dinnerboned'? Do you put a name tag on it? Do you use any plugins?
Which plugin version do you use? What is the server version?
Finally, please send me all the .yml files in the plugin folder.

**Comment by DavideBlade** [comment]
No response. Bug not reproducible/wrongly opened.
