### ISSUE TITLE
Inquiry regarding the health bar display.

### ISSUE THREAD

**Issue by Cetch000** [DavideBlade/HealthBar-Reloaded#12]
When you first hit, it shows 'Mob name HP' but after that, it only shows 'HP'. Also, in chat, when a mob is killed, only the health bar appears, so I don't know who killed it.

![2024-05-24_23 21 02](https://github.com/DavideBlade/HealthBar-Reloaded/assets/170740506/6fb9b01f-008c-43e0-a285-2e1ef115c866)

**Comment by DavideBlade** [comment]
What is the server version? Plugin version?
Please send me all the .yml files in the plugin folder.

**Comment by DavideBlade** [comment]
No response. Bug not reproducible/wrongly opened.
