### ISSUE TITLE
Add integration for AuraMobs

### ISSUE THREAD

**Issue by Raidware** [DavideBlade/HealthBar-Reloaded#14]
like levelledmobs, mythic mobs

**Comment by DavideBlade** [comment]
I looked at the source code and found what I need even though it is not part of the API. Unfortunately, however, there is a total lack of documentation for the integration (not even on Discord), and I need some information from the developer. I have contacted him and am waiting for a response.

**Comment by DavideBlade** [comment]
AuraMobs has been published on Maven by the developer. From version 2.0.3.7 the integration will be available on HealthBar.
