### ISSUE TITLE
How to create Custom Bars

### ISSUE THREAD

**Issue by bxnAcc** [DavideBlade/HealthBar-Reloaded#15]
Hey I read the wiki but do not understand what I need to do to create a custom healthbar

Because I created a file in wich I copied the text of the wiki, put it in the Haltbar Folder and seted the use-custom-file: to true

**Comment by DavideBlade** [comment]
The file is created automatically, no need to create it manually. There are (incomplete) examples in the "[Custom file](https://github.com/DavideBlade/HealthBar-Reloaded/wiki/Customization#custom-file)" section.
If you created it yourself, delete the _custom-mob-bar.yml_ file, set `use-custom-file: true` and start the server. The custom file will appear in the plugin's folder, and you can edit it from there.

**Comment by DavideBlade** [comment]
Did I answer your question?
