### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by bxnAcc** [DavideBlade/HealthBar-Reloaded#16]
Hey i tested all the custom Health-Bar Plugins i could find but yours is still the best for my needs.

But still there a some things i would be happy about of you could add them 

- Multi line Support for mythicmobs (currently the Name of the mob just gets Overwriten by the healthbar! It would be cooler to have it bellow the Name)
- Placeholder Support for custom Health-Bars (You can See how Many lives the mob still have and not just percent)

**Comment by DavideBlade** [comment]
Hi, yesterday I developed an [update](https://github.com/DavideBlade/HealthBar-Reloaded/commit/952f14ce7cc4fd1381b8291cb918711e6a39a6a9#commitcomment-144439719) (in beta) to append the health bar to mobs with already a custom name. From version 2.0.3.9 it will be available. However, it's not possible to add more lines to mobs, as you can read from the [wiki](https://github.com/DavideBlade/HealthBar-Reloaded/wiki/FAQ).

For the second point, I'm not sure I understand: do you want to see the number of hearts a mob has? If so, why doesn't [text-mode](https://github.com/DavideBlade/HealthBar-Reloaded/wiki/Customization#text-mode-1) work for you?
