### ISSUE TITLE
Multi-line support & locale.yml

### ISSUE THREAD

**Issue by moodhopelessness** [DavideBlade/HealthBar-Reloaded#17]
In one of your posts here you linked to a wiki that says there is no multiline feature.

"However, it's not possible to add more lines to mobs, as you can read from the wiki."

Is this your personal opinion and reluctance to add this feature to the plugin? Or is it technically impossible? This feature would be a great addition to the plugin, it's a strong visual upgrade for Minecraft.

By the way, what is the locale.yml file for? I tried renaming vanilla mobs, but the plugin doesn't use their names from this file.

**Comment by DavideBlade** [comment]
> In one of your posts here you linked to a wiki that says there is no multiline feature.
> 
> "However, it's not possible to add more lines to mobs, as you can read from the wiki."
> 
> Is this your personal opinion and reluctance to add this feature to the plugin? Or is it technically impossible? This feature would be a great addition to the plugin, it's a strong visual upgrade for Minecraft.

It is a limitation of the Minecraft mechanisms on which the plugin is based. There is no such possibility as there is for players (with its limitations).
There can at most be workarounds, such as the use of invisible entities, but, more or less, inefficient, ugly and complex to manage, especially if you want to implement them in the right way that doesn't _crash_ a medium/large server in a few hours. That's outside the scope of this plugin.

Out of curiosity, what would you use these multiple lines for? What would you add to them?
<br/>

> By the way, what is the locale.yml file for? I tried renaming vanilla mobs, but the plugin doesn't use their names from this file.

Its main purpose is to provide a way to translate (not necessarily into different languages, but just to give custom names) the names of entities when displayed with the custom-text method. You can see some example screenshots [here](https://github.com/DavideBlade/HealthBar-Reloaded/wiki/Customization#custom-text-mode).

**Comment by moodhopelessness** [comment]
> It is a limitation of the Minecraft mechanisms on which the plugin is based. There is no such possibility as there is for players (with its limitations).
> There can at most be workarounds, such as the use of invisible entities, but, more or less, inefficient, ugly and complex to manage, especially if you want to implement them in the right way that doesn't crash a medium/large server in a few hours. That's outside the scope of this plugin.

Okay, thanks for the prompt response, appreciate it! I really didn't expect such speed.


> Out of curiosity, what would you use these multiple lines for? What would you add to them?

Purely visual beauty. I am creating a server like some kind of RPG specifically on vanilla Minecraft. And I would like to see a beautiful display of mob HP, your plugin at the moment seemed to me to be the highest quality and without unnecessary functions (only for my server. For example, LeveledMobs has a lot of them, which I do not use). "Name - HP / Max HP" is already good, but the ideal would be "Name" and "HP" in two different lines, as is done by players. I think it looks much more beautiful. But, unfortunately, vanilla Minecraft does not always work out the way you want.


> Its main purpose is to provide a way to translate (not necessarily into different languages, but just to give custom names) the names of entities when displayed with the custom-text method. You can see some example screenshots [here](https://github.com/DavideBlade/HealthBar-Reloaded/wiki/Customization#custom-text-mode).

I don't know if I understood you correctly. Are these custom names used only inside the plugin files, or do they allow you to translate the entity's display name in the game? Using it as a translation didn't work for me for some reason, I'll try in a few days when I get home.

Thanks again for your activity! Good luck in your development!

**Comment by DavideBlade** [comment]
They function as a translation for everything used by the plugin. I ran a test just to confirm and it works (almost) correctly. Apparently there is a small bug that I will fix in the next version.

Try the following configurations.
config.yml:
```yaml
...
mob-bars:
  enable: true
  always-shown: true
  text-mode: true
  custom-text-enable: true
  custom-text: '{name} - &a{health}/{max}'
...
```

locale.yml:
```yaml
...
SHEEP: TEST123
...
```

Start the server, spawn a sheep, and hit it once. You will see the custom name.

<br/>
I will leave the ticket open until the bug is fixed. In case something doesn't work for you, let me know.

**Comment by moodhopelessness** [comment]
if "always-shown:" set to false, names from locale.ymlfrom were not changed. now I set it to true and its works but.. when i just looking on mob it has default name (i have show-only-if-looking: true)

![Снимок экрана 2024-07-29 175542](https://github.com/user-attachments/assets/eff0cb8f-e809-44ea-9edf-af717634ba0e)

and when i hit it name becomes correct

![Снимок экрана 2024-07-29 175642](https://github.com/user-attachments/assets/62ffe8f4-ff80-4bbe-be06-668eb2587516)

Is this the bug you were talking about?

**Comment by DavideBlade** [comment]
The bug consists in the fact that the newly spawned entity has its original vanilla name instead of the translated one. The translated name is only set after 1 or 2 (depending on `always-shown`) hits.
In 2.0.4.1 it is fixed.

**Comment by DavideBlade** [comment]
Update released, let me know if there are any other problems.

**Comment by moodhopelessness** [comment]
Everything is clear. Thank you!
