### ISSUE TITLE
About delete plugin HealthBar-Reloaded

### ISSUE THREAD

**Issue by DimazWayne** [DavideBlade/HealthBar-Reloaded#18]
interestingly, when entering the game, all NPCs always have hp, but after I enter the mbedwars lobby and then back to the hub, everything is deleted. Anyway i delete your plugin, but display hp is stayed
![healtй](https://github.com/user-attachments/assets/72c0062c-7ada-424e-b140-3628cb58319d)

**Comment by DavideBlade** [comment]
So, if I understand correctly what you do is:
1. Install my plugin
2. Start the server
3. Join the server where the NPCs are located
4. Display the health bar correctly (e.g. 100% health)
5. Delete the .jar of my plugin
6. Restart the server
7. Continue to see the health bar but with 0%?

Is this correct?

Which version of Spigot are you using? And which version of the plugin? Which plugin are you using for NPCs?
Can you send me the output of `/plugins`? (after removing the plugin .jar)

**Comment by DavideBlade** [comment]
Also, I see another NPC on the left in the picture. That one doesn't seem to have a health bar. Is that correct? Is it a different type?

**Comment by DimazWayne** [comment]
The problem is solved, a friend helped me solve it. As I understand it, your plugin somehow saves data to the TAB plugin, she deleted everything there that was related to your plugin

**Comment by DavideBlade** [comment]
The plugin does not store anything persistently. It is possibly Tab that stores what was there before (with its pros and cons).
Glad the problem has been solved. Have a good day :)
