### ISSUE TITLE
When I use plugin tab this plugin is not working

### ISSUE THREAD

**Issue by sdawd2q3e** [DavideBlade/HealthBar-Reloaded#5]
When I use plugin tab this plugin is not working

**Comment by sdawd2q3e** [comment]
https://modrinth.com/plugin/tab-was-taken

**Comment by sdawd2q3e** [comment]
Placeholders do not work

**Comment by DavideBlade** [comment]
It is likely that the reason is because this plugin also uses Scoreboards and so they conflict. I will try to contact the developer to see what can be done but there may be no workable solution.

**Comment by DavideBlade** [comment]
Can you send me screenshots of what the tab looks like when you are not using HealthBar and when it is present?

**Comment by sdawd2q3e** [comment]
It shows only the things that you put in the tab only, but heal does not work. Try that and you will see what happens

**Comment by sdawd2q3e** [comment]
Did you find a solution to the problem?

**Comment by DavideBlade** [comment]
I could not find the developer's contact through any channel, so the problem is currently stalled. I will have to study the plugin and that will take quite some time.

**Comment by DavideBlade** [comment]
If support is still needed, please provide me with a screenshot explaining where the problem is. I am not familiar with the plugin and have never used it, so I don't know what works or what doesn't.
Also, what version of the plugins and Spigot are you using? What is your configuration?

**Comment by DavideBlade** [comment]
No answer. Closing.
