### ISSUE TITLE
WildStacker support

### ISSUE THREAD

**Issue by DavideBlade** [DavideBlade/HealthBar-Reloaded#7]
[fabricio9898](https://www.spigotmc.org/members/fabricio9898.440987/) ask on [Spigot](https://www.spigotmc.org/threads/healthbar-reloaded.569736/#post-4661515) to add support for the plugin [WildStacker](https://www.spigotmc.org/resources/%E2%9A%A1%EF%B8%8F-wildstacker-%E2%9A%A1%EF%B8%8F-spawners-entities-drops-blocks-%E2%9A%A1%EF%B8%8F-1-20-2-support.87404/) (plugin documentation: https://bg-software.com/wildstacker/).

**Comment by SrMonsterYT** [comment]
it's me here, thank you for caring about my suggestion

**Comment by SrMonsterYT** [comment]
@DavideBlade sorry to ask, do you have a date for when wildstacker will be supported?

**Comment by DavideBlade** [comment]
Sorry, but unfortunately not. I don't like that as an answer, but I would rather not give any date than to give a date and not meet it.

**Comment by DavideBlade** [comment]
What should the support consist of? Where is the problem? When does it occur?

**Comment by SrMonsterYT** [comment]
> What should the support consist of? Where is the problem? When does it occur?

the mob count looks like this, buggy https://youtu.be/HJHKK7CBO5g

**Comment by DavideBlade** [comment]
So the bar should be hidden on the stacked mobs?

**Comment by SrMonsterYT** [comment]
> So the bar should be hidden on the stacked mobs?

this hasn't been fixed yet i'm using version 2.0.3.8 and the same problem as in the video above

**Comment by DavideBlade** [comment]
> this hasn't been fixed yet i'm using version 2.0.3.8 and the same problem as in the video above

Did you set `WildStacker: true` in the config?

**Comment by SrMonsterYT** [comment]
> > this hasn't been fixed yet i'm using version 2.0.3.8 and the same problem as in the video above
> 
> Did you set `WildStacker: true` in the config?

I defined it, but there's a problem, when they're grouped together it doesn't show how much life they have, it only shows when it's 1 mob

video: https://youtu.be/8H2l-lvsPas

**Comment by DavideBlade** [comment]
Yes, this is the expected behavior: when mobs are not stacked you can show it because the nametag set by WildStacker is not present.
I can try to set the health bar next to the tag set by WildStacker but it may not be possible because of some length limitations imposed by Minecraft.
Also, in addition to that is to evaluate compatibility: on HealthBar you can configure timers after which the bar should be removed while on WildStacker the bar has different timings.
Finally, it is not necessarily the case that WildStacker offers APIs for changing the tag.

**Comment by DavideBlade** [comment]
Further integration requested

**Comment by SrMonsterYT** [comment]
> Yes, this is the expected behavior: when mobs are not stacked you can show it because the nametag set by WildStacker is not present. I can try to set the health bar next to the tag set by WildStacker but it may not be possible because of some length limitations imposed by Minecraft. Also, in addition to that is to evaluate compatibility: on HealthBar you can configure timers after which the bar should be removed while on WildStacker the bar has different timings. Finally, it is not necessarily the case that WildStacker offers APIs for changing the tag.

is it possible to place HealthBar placeholderapi?, in wildstacker

**Comment by DavideBlade** [comment]
I took a look at the PlaceholderAPI integration and it might be doable, but that still wouldn't solve the WildStacker problem since, at least from the documentation I read, it doesn't seem to support the plugin.

**Comment by DavideBlade** [comment]
I took a look at the PlaceholderAPI integration and it might be doable, but that still wouldn't solve the WildStacker problem since, at least from the documentation I read, it doesn't seem to support the plugin.

**Comment by DavideBlade** [comment]
I also checked the [WildStacker API](https://bg-software.com/wildstacker/api/) and it is possible to change the name displayed above an entity configured via WildStacker, so I could potentially, for example, place the health bar to the right or left of the tag set by WildStacker.

However, this will not be implemented for the reasons given above:
1) HealthBar has its own configurable timers to set the health bar visible only for a period of time while WildStacker does not: I would have to track all WildStacker mobs on which I have set a temporary health bar (without an API, since this is not a supported operation, so subject to potential change at any time) in a totally different way than the tracking method currently used and then later change only the health bar portion of the tag so as not to affect the WildStacker tag
2) WildStacker could one day decide to insert timers to display its tag only for a period of time: this would further complicate the situation, since without an integration by the WildStacker developers towards HealthBar, it could remove the entire custom name, containing both the health bar and the WildStacker tag (HealthBar should therefore take care of checking every second if the health bar has been removed from the WildStacker mobs tracked with the method in point 1 - definitely out of its scope)
This inevitably leads to a greater consumption of resources for the server and to a considerable amount of work and to an obligation on my part to constantly monitor WildStacker updates. Which is clearly not possible: imagine having to check the updates of every single plugin on which HealthBar is integrated.

**Comment by DavideBlade** [comment]
As a last option, in case this is configurable by WildStacker (please confirm it), is to set the health bar also on stacked mobs, as long as they do not have the tag.
HealthBar currently checks the amount of stacked entities, and if it is greater than 1, it does not set the health bar. I could replace this check with one that checks if the mob has the tag visible/set by WildStacker and, if not, sets the health bar.

Not an ideal solution, since users will no longer have any idea which mobs are stacked and how many there are, but unfortunately, it's the only solution I can think of with what we have available.

**Comment by DavideBlade** [comment]
Another viable option is to request WildStacker developers to integrate with HealthBar. With the API available, there should be no problem.

**Comment by SrMonsterYT** [comment]
> Another viable option is to request WildStacker developers to integrate with HealthBar. With the API available, there should be no problem.

actually there is a solution yes, the HoloMobHealth plugin does it right whenever there is 1 mob it shows the amount, I just removed this plugin because it causes performance problems to the server is poorly optimized, if he succeeded and because you can too

image plugin: https://prnt.sc/ocPRkNSrfyl3

that's why I abandoned it because of its performance https://prnt.sc/ABjQuWqc_hea

**Comment by DavideBlade** [comment]
I didn't say it's not possible, just that it's not worth the time spent on it, especially given the fact that it could break at any moment due to not using the API (I checked and HoloMobHealth doesn't interact with WildStacker in any way).

I will not sacrifice code maintainability or plugin performance to forcefully add integration where it doesn't fit.

In any case I will try to think of something else. Certainly, there won't be any developments before 2-4 weeks.

**Comment by SrMonsterYT** [comment]
> I didn't say it's not possible, just that it's not worth the time spent on it, especially given the fact that it could break at any moment due to not using the API (I checked and HoloMobHealth doesn't interact with WildStacker in any way).
> 
> I will not sacrifice code maintainability or plugin performance to forcefully add integration where it doesn't fit.
> 
> In any case I will try to think of something else. Certainly, there won't be any developments before 2-4 weeks.

this has been requested since 2023, I have already abandoned the idea of using this plugin, unfortunately I only dare that it will be done after months and months, well the plugin does not support one of the main plugins of wildstacker entities, nevertheless thank you for your attention if you want you can close this report

**Comment by DavideBlade** [comment]
I am a human being; I do what I can do in the time I have. Plugins are a hobby, not a job.

If you don't want to use the plugin, I'm sorry, but the hours in a day are 24 for everyone.

The issue will remain open as it could serve for a larger change to the plugin that could allow more use along with other plugins. Thanks for your suggestions.

**Comment by SrMonsterYT** [comment]
> I am a human being; I do what I can do in the time I have. Plugins are a hobby, not a job.
> 
> If you don't want to use the plugin, I'm sorry, but the hours in a day are 24 for everyone.
> 
> The issue will remain open as it could serve for a larger change to the plugin that could allow more use along with other plugins. Thanks for your suggestions.

ok friend I understand that you have a life, but this has been open since 2023, nevertheless sorry for anything and have a great day.

**Comment by DavideBlade** [comment]
In beta, the ability to append the bar to entities that already have a custom name will be added. This functionality will, at least initially, be independent of any plugins, that is, it will not integrate with any third-party API. Should there be any problems with third-party plugins overwriting the custom name without keeping the health bar appended, integration will be evaluated.
The `config.yml` will be modified as follows.

Current version (v2.0.3.8):
```yaml
# Should the bar be shown on renamed mobs?
show-on-named-mobs: true
```

Next version (v2.0.3.9):
```yaml
# Should the bar be shown on renamed mobs? If so, how?
# You can choose between "override", "append", and "no".
# Note: The “append” option is in beta.
show-on-named-mobs: override
```

**Comment by SrMonsterYT** [comment]
> ```yaml
> override
> ```

thanks for worrying about it, but there's still a problem, how do i get it to look like this?

wildstackername - health symbol

when it gets to the last mob it doesn't display the mob's name

https://youtu.be/y3OciGaVJzc

my config: https://mclo.gs/yv7tvra

how do I always leave it like this, even if there's only 1 mob: https://imgur.com/IKCWa2g

**Comment by DavideBlade** [comment]
From the HealthBar config you can't, it's something I must fix in the code. This is one of the problems I expected to occur without integration. From the commit in fact:
> This update **partially** solves #7.

<br/>
If from WildStacker you can configure the tag to start from a single unit (i.e., to always be shown), you should be able to fix (at least temporarily) the problem until the next update.

**Comment by DavideBlade** [comment]
I identified the problem: it was not caused by WildStacker contrary to what I thought, it just highlighted it. It will be fixed in version 2.0.4 published today. Please let me know if everything is ok.

**Comment by SrMonsterYT** [comment]
> I identified the problem: it was not caused by WildStacker contrary to what I thought, it just highlighted it. It will be fixed in version 2.0.4 published today. Please let me know if everything is ok.

it worked thanks, one question is it possible to make it change color like green, yellow and red, in this type of format?

video: https://youtu.be/k3va8xSv9Vs

config: https://mclo.gs/WkTA5ml

**Comment by DavideBlade** [comment]
I assume you are referring to giving a different color based on the criticality of the health available. In custom text mode this is not possible.
As an alternative you can use the custom file, though this works as % of health and not with the exact number of hearts.

**Comment by SrMonsterYT** [comment]
> I assume you are referring to giving a different color based on the criticality of the health available. In custom text mode this is not possible. As an alternative you can use the custom file, though this works as % of health and not with the exact number of hearts.

ok thanks!
