### ISSUE TITLE
HealthBar-Reloaded 2.0.3.2

### ISSUE THREAD

**Issue by Anexius23** [DavideBlade/HealthBar-Reloaded#8]
Hello. I downloaded the HealthBar-Reloaded 2.0.3.2 plugin and installed Paper 1.20.4 on the server. Everything works, everything shows, when I want to change the config to have my text, the plugin stops working. Otherwise everything works. 
![2024-02-28_21 26 38](https://github.com/DavideBlade/HealthBar-Reloaded/assets/161644551/a39f4f60-5ca2-43d8-be89-5214bd3035e4)
![2024-02-28_21 27 01](https://github.com/DavideBlade/HealthBar-Reloaded/assets/161644551/f02d0fbe-01fa-403c-8bc9-199ae9a48964)
![2024-02-28_21 34 12](https://github.com/DavideBlade/HealthBar-Reloaded/assets/161644551/687b76b0-814f-4e19-8bd3-2a7c20ff190c)
<img width="1280" alt="Снимок экрана 2024-02-28 213208" src="https://github.com/DavideBlade/HealthBar-Reloaded/assets/161644551/4f1a869d-94e4-45d1-b69e-6a346ebc3bbf">

**Comment by DavideBlade** [comment]
Thank you for the report. From the next version it will be fixed 😄

**Comment by Anexius23** [comment]
Hello. Everything works fine,  but why is there so much flooding in the console, is it the plugin’s fault or the server’s?
<img width="674" alt="Без имени" src="https://github.com/DavideBlade/HealthBar-Reloaded/assets/161644551/490c41e9-52ac-452a-b455-526537d7219b">

**Comment by DavideBlade** [comment]
At least this one is only cosmetic :see_no_evil:
I will fix it in the next version

**Comment by DavideBlade** [comment]
@Anexius23 Please try this version: https://file.io/dn4ZLgqsqy4C. The link will only allow you to download the file once and will expire in three days.

**Comment by Anexius23** [comment]
unfortunately I didn't have time to download it :{

**Comment by DavideBlade** [comment]
@Anexius23 Now available for 1 week: https://file.io/D0QknV147s4N

**Comment by Anexius23** [comment]
thank you )))
