### ISSUE TITLE
Player health doesn't work

### ISSUE THREAD

**Issue by Bulgus** [DavideBlade/HealthBar-Reloaded#9]
When I reload the plugin, the health of players appear and disappear after 1 secondes... I think don't have any plugin that could be replace players names : 
![image](https://github.com/DavideBlade/HealthBar-Reloaded/assets/88266443/13ff91cb-2664-49ca-86c9-a2475c4130d3)

Paper 1.20.4
``

**Comment by DavideBlade** [comment]
What version of the plugin are you using? Please send me all .yml files of HealthBar (you can paste them into PasteBin or upload the file directly).

**Comment by Bulgus** [comment]
Here is my config.yml : 

https://pastebin.com/YFJUsF8H

Version 2.0.3.3

**Comment by DavideBlade** [comment]
I tested your config and have no problem keeping the health bar fixed.
My advice for figuring out which plugin(s) are interfering is to try removing and putting in plugins until you get the expect behavior. Then, if you want, let me know which one it is so I can update the list of incompatible plugins.

**Comment by Bulgus** [comment]
I found it... It was Simple TabList (https://www.spigotmc.org/resources/%E2%98%86-simple-tablist-%E2%98%86%E3%80%8A1-16-x-1-20-x%E3%80%8B-animated-hex-colors.101989/)... but I don't understand why it break HealthBar Reloaded

**Comment by DavideBlade** [comment]
Thanks for the report. I'll add it to the list of non-compatible plugins for the time being. If the developer one day adds an API, maybe something can be done to make them compatible.
